---
# tasks file for mlnx-ofed
- shell: ofed_info -n
  register: ofed_version
  ignore_errors: True

- debug:
    msg: "MLNX OFED version {{ ofed_version }}"

- include: mlnx-ofed-install.yml
  when: ofed_version is failed or ofed_version.stdout != mlnx_ofed_version

