---
# tasks file for mlnx-ofed
- name: Check currently installed MLNX OFED version
  command: ofed_info -n
  register: ofed_version
  changed_when: false
  ignore_errors: True

- name: Output recorded version
  debug:
    msg: "MLNX OFED version {{ ofed_version }}"

- include: mlnx-ofed-install.yml
  when: ofed_version is failed or ofed_version.stdout != mlnx_ofed_version

