- name: Download MLNX OFED iso
  become: yes
  get_url:
    url: "{{ mlnx_ofed_url }}"
    dest: "{{ mlnx_ofed_iso_filename }}"
    mode: 0755
    checksum: "{{ mlnx_ofed_iso_checksum }}"
  when: mlnx_ofed_local_file is not defined

- name: Copy local MLNX OFED iso
  become: yes
  copy:
    src: "{{ mlnx_ofed_local_file }}"
    dest: "{{ mlnx_ofed_iso_filename }}"
    mode: 0755
    checksum: "{{ mlnx_ofed_iso_checksum }}"
  when: mlnx_ofed_local_file is defined

- name: Temporarily mount MLNX OFED iso
  mount:
    state: mounted
    boot: no
    path: /mnt/mlnx_ofed
    src: "{{ mlnx_ofed_iso_filename }}"
    fstype: iso9660
  become: yes

- name: apt update
  apt: update_cache=yes

- name: Install package dependencies
  package:
    name:
      - perl
      - dpkg
      - autotools-dev
      - autoconf
      - libtool
      - automake
      - m4
      - dkms
      - debhelper
      - tcl
      - chrpath
      - swig
      - graphviz
      - tcl-dev
      - tk-dev
      - bison
      - flex
      - dpatch
      - zlib1g-dev
      - curl
      - libcurl4-gnutls-dev
      - python-libxml2
      - libvirt0
      - libnl-3-dev
      - libnl-route-3-dev
      - libglib2.0-dev
      - pkg-config
      - libnuma-dev
      - logrotate
      - ethtool
      - lsof
    state: latest
  become: yes

- name: Ubuntu 18.04 specific packages
  package:
    name:
      - libvirt-bin
      - libgfortran3
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic'

- name: libvirt clients (Ubuntu 20.04)
  package: name=libvirt-clients
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'focal'

- name: Run MLNX OFED installation script
  command: "/mnt/mlnx_ofed/mlnxofedinstall --vma --upstream-libs --force"
  become: yes
  register: mlnxofedinstallout
  changed_when: mlnxofedinstallout.rc == 0

- name: Unmount MLNX OFED iso
  mount:
    state: unmounted
    path: /mnt/mlnx_ofed
  become: yes
