- name: Download MLNX OFED iso
  become: yes
  get_url:
    url: "{{ mlnx_ofed_url }}"
    dest: "{{mlnx_ofed_iso_filename}}"
    mode: 0755
    checksum: "{{ mlnx_ofed_iso_checksum }}"

- mount:
    state: mounted
    boot: no
    path: /mnt/mlnx_ofed
    src: "{{mlnx_ofed_iso_filename}}"
    fstype: iso9660
  become: yes

- name: apt update
  apt: update_cache=yes

- package:
    name:
      - perl
      - dpkg
      - autotools-dev
      - autoconf
      - libtool
      - automake
      - m4
      - dkms
      - debhelper
      - tcl
      - chrpath
      - swig
      - graphviz
      - tcl-dev
      - tk-dev
      - bison
      - flex
      - dpatch
      - zlib1g-dev
      - curl
      - libcurl4-gnutls-dev
      - python-libxml2
      - libvirt-bin
      - libvirt0
      - libnl-3-dev
      - libnl-route-3-dev
      - libglib2.0-dev
      - libgfortran3
      - pkg-config
      - libnuma-dev
      - logrotate
      - ethtool
      - lsof
    state: latest
  become: yes

- command: "/mnt/mlnx_ofed/mlnxofedinstall --vma --upstream-libs --force"
  become: yes

- mount:
    state: unmounted
    path: /mnt/mlnx_ofed
  become: yes
